% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}

% foodgroup availability ratio
\includepdfmerge[nup=2x3]{
foodAvail_foodGroup_fruits_tenregions.pdf, foodAvail_foodGroup_meats_tenregions.pdf,
foodAvail_foodGroup_nutsNseeds_tenregions.pdf, foodAvail_foodGroup_oils_tenregions.pdf,
foodAvail_foodGroup_pulses_tenregions.pdf, foodAvail_foodGroup_rootsNPlaintain_tenregions.pdf
}

\end{document}

