% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}

% vitamin adequacy ratio
\includepdfmerge[nup=2x3]{vits_reqRatio_folate_µg_tenregions.pdf,vits_reqRatio_niacin_mg_tenregions.pdf,vits_reqRatio_riboflavin_mg_tenregions.pdf,vits_reqRatio_thiamin_mg_tenregions.pdf,vits_reqRatio_vit_a_rae_µg_tenregions.pdf,vits_reqRatio_vit_b6_mg_tenregions.pdf,vits_reqRatio_vit_b12_µg_tenregions.pdf,vits_reqRatio_vit_c_mg_tenregions.pdf,vits_reqRatio_vit_d_µg_tenregions.pdf,vits_reqRatio_vit_e_mg_tenregions.pdf,vits_reqRatio_vit_k_µg_tenregions.pdf}
\end{document}

