% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}

% foodgroup availability ratio
\includepdfmerge[nup=2x3]{
foodAvail_foodGroup_fruits_WB.pdf, foodAvail_foodGroup_meats_WB.pdf, 
foodAvail_foodGroup_nutsNseeds_WB.pdf, foodAvail_foodGroup_oils_WB.pdf, 
foodAvail_foodGroup_pulses_WB.pdf, foodAvail_foodGroup_rootsNPlaintain_WB.pdf
}

\end{document}

