% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}
% macro nutrients adequacy ratio
\includepdfmerge[nup=2x2]{carbohydrate_g_macro_reqRatio_WB.pdf, protein_g_macro_reqRatio_WB.pdf, totalfiber_g_macro_reqRatio_WB.pdf}

% mineral nutrients adequacy ratio
\includepdfmerge[nup=2x3]{calcium_mg_minrls_reqRatio_WB.pdf,folate_µg_vits_reqRatio_WB.pdf,iron_mg_iron_bioavail_reqRatio_WB.pdf,
                        magnesium_mg_minrls_reqRatio_WB.pdf, phosphorus_mg_minrls_reqRatio_WB.pdf, potassium_g_minrls_reqRatio_WB.pdf,
                        zinc_mg_zinc_bioavail_reqRatio_WB.pdf}

% vitamin adequacy ratio
\includepdfmerge[nup=2x3]{niacin_mg_vits_reqRatio_WB.pdf, riboflavin_mg_vits_reqRatio_WB.pdf,
                      thiamin_mg_vits_reqRatio_WB.pdf, vit_a_rae_µg_vits_reqRatio_WB.pdf, vit_b6_mg_vits_reqRatio_WB.pdf,
                      vit_b12_µg_vits_reqRatio_WB.pdf, vit_c_mg_vits_reqRatio_WB.pdf, vit_d_µg_vits_reqRatio_WB.pdf,
                      vit_e_mg_vits_reqRatio_WB.pdf, vit_k_µg_vits_reqRatio_WB.pdf}

% foodgroup availability ratio
\includepdfmerge[nup=2x3]{alcohol_foodAvail_foodGroup_WB.pdf, beverages_foodAvail_foodGroup_WB.pdf,
                           cereals_foodAvail_foodGroup_WB.pdf, dairy_foodAvail_foodGroup_WB.pdf,
                           eggs_foodAvail_foodGroup_WB.pdf, fish_foodAvail_foodGroup_WB.pdf, fruits_foodAvail_foodGroup_WB.pdf,
                           meats_foodAvail_foodGroup_WB.pdf, nutsNseeds_foodAvail_foodGroup_WB.pdf, oils_foodAvail_foodGroup_WB.pdf,
                           pulses_foodAvail_foodGroup_WB.pdf, rootsNPlaintain_foodAvail_foodGroup_WB.pdf,
                           sweeteners_foodAvail_foodGroup_WB.pdf, vegetables_foodAvail_foodGroup_WB.pdf}

\end{document}

