% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}

% mineral nutrients adequacy ratio
\includepdfmerge[nup=2x3]{minrls_reqRatio_calcium_mg_tenregions.pdf,
minrls_reqRatio_iron_mg_tenregions.pdf,minrls_reqRatio_magnesium_mg_tenregions.pdf,
minrls_reqRatio_phosphorus_mg_tenregions.pdf,minrls_reqRatio_potassium_g_tenregions.pdf,
minrls_reqRatio_zinc_mg_tenregions.pdf}

\end{document}

