% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}

% foodgroup availability ratio
\includepdfmerge[nup=2x3]{
fruits_foodAvail_foodGroup_WB.pdf, meats_foodAvail_foodGroup_WB.pdf,
nutsNseeds_foodAvail_foodGroup_WB.pdf, oils_foodAvail_foodGroup_WB.pdf,
pulses_foodAvail_foodGroup_WB.pdf, rootsNPlaintain_foodAvail_foodGroup_WB.pdf
}

\end{document}

