% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}

% foodgroup availability ratio
\includepdfmerge[nup=2x3]{
foodAvail_foodGroup_alcohol_tenregions.pdf,
foodAvail_foodGroup_beverages_tenregions.pdf, foodAvail_foodGroup_cereals_tenregions.pdf,
foodAvail_foodGroup_dairy_tenregions.pdf, foodAvail_foodGroup_eggs_tenregions.pdf,
foodAvail_foodGroup_fish_tenregions.pdf
}
\end{document}

