% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}
% macro nutrients adequacy ratio
\includepdfmerge[nup=2x3]{
fat_g_AMDR_lo_tenregions.pdf, fat_g_AMDR_hi_tenregions.pdf,
carbohydrate_g_AMDR_lo_tenregions.pdf,carbohydrate_g_AMDR_hi_tenregions.pdf,
protein_g_AMDR_lo_tenregions.pdf, protein_g_AMDR_hi_tenregions.pdf}

\end{document}

