% from http://tex.stackexchange.com/questions/5228/can-one-tex-file-output-to-multiple-pdf-files
\documentclass{article}
\usepackage{pdfpages}
\begin{document}
% macro nutrients adequacy ratio
\includepdfmerge[nup=2x2]{
%AMDR_lo_carbohydrate_g_tenregions.pdf, AMDR_hi_carbohydrate_g_tenregions.pdf,
%AMDR_lo_protein_g_tenregions.pdf, AMDR_hi_protein_g_tenregions.pdf,
%AMDR_lo_fat_g_tenregions.pdf, AMDR_hi_fat_g_tenregions.pdf
%}
AMDRShare_carbohydrate_g_tenregions.pdf,
AMDRShare_protein_g_tenregions.pdf,
AMDRShare_fat_g_tenregions.pdf
}
\end{document}

