#' @author Gerald C. Nelson, \email{nelson.gerald.c@@gmail.com}
#' @keywords nutrient data,
#' @title Import and process DSSAT yield data
#' @name dataPrepYields.R
#' @include nutrientModFunctions.R

#' @keywords DSSAT, yield, data
#' @description
#' This script imports DSSAT yield data generated by Ricky Robertson

#Copyright (C) 22018 Gerald C. Nelson, except where noted

# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details at http://www.gnu.org/licenses/.

source("R/nutrientModFunctions.R")
library(RColorBrewer)
# next 3 libraries needed for world maps
library(sp)
library(broom)
library(rgdal)
library(readr)
library(rgeos)
sourceFile <- "dataPrepYields.R"
createScriptMetaData()


worldMap <- getNewestVersion("worldMap", fileloc("uData"))
africaMap <- getNewestVersion("africaMap", fileloc("uData"))
asiaMap <- getNewestVersion("asiaMap", fileloc("uData"))
fpusMap <- getNewestVersion("fpusMap", fileloc("uData"))
fpusMap_SSA <- getNewestVersion("fpusMap_SSA", fileloc("uData"))




# fpusMap@data$region <- rownames(fpusMap@data)
# fpusMap@data$USAFPU <- NULL # probably not necessary to do this.
# fpusMap <- spTransform(fpusMap, CRS("+proj=wintri")) # see http://rpsychologist.com/working-with-shapefiles-projections-and-world-maps-in-ggplot
# fpusMap <- gBuffer(fpusMap, byid=TRUE, width=0)
# fpusMap <- broom::tidy(fpusMap, region = "FPU2015") # causes errors because of binding character and factor vector, but I don't know where the factor vector is

# get the grid for a world map
gratDir <- paste0(getwd(), "/data-raw/data-gis/ne_110m_graticules_all")
grat <- readOGR(gratDir, layer="ne_110m_graticules_15") 
grat_df <- broom::tidy(grat)

# get the bounding box for a world map
bbox <- readOGR(gratDir, layer="ne_110m_wgs84_bounding_box") 
bbox_df<- broom::tidy(bbox)

ggplot(bbox_robin_df, aes(long,lat, group=group)) + 
  geom_polygon(fill="white") +
  geom_polygon(data=fpusMap, aes(long,lat, group=group, fill=hole)) + 
  geom_path(data=grat_df_robin, aes(long, lat, group=group, fill=NULL), linetype="dashed", color="grey50") +
  labs(title="World map (Robinson)") + 
  coord_equal() + 
  theme_opts +
  scale_fill_manual(values=c("black", "white"), guide="none") # change colors & remove legend


dt.complete <- as.data.table(read_csv("data-raw/yields/dssat_379_sorg_base_hadgem2_es_rcp8p5_2050.csv", col_names=TRUE, cols(
  CCCOM = col_character(),
  FPU = col_character(),
  IRRF = col_character(),
  YRS = col_integer(),
  co2_level = col_integer(),
  area = col_double(),
  yield = col_double(),
  prod = col_double(),
  adopt_area = col_integer(),
  post_adopt_yield = col_integer(),
  post_adopt_prod = col_integer(),
  pre_adopt_yield = col_integer(),
  pre_adopt_prod = col_integer(),
  nonadopt_area = col_double(),
  nonadopt_yield = col_double(),
  nonadopt_prod = col_double())))

# do aggregation to country
dt <- copy(dt.complete)
dt[, region_code.IMPACT159 := substring(FPU,5,7)]
dt <- countryCodeCleanup(dt)
#dt[, yield.cty := sum(yield), by = c("region_code.IMPACT159", "IRRF")]
dt[, value := weighted.mean(yield, prod), by = c("region_code.IMPACT159", "IRRF")]
dt <- dt[, c("FPU", "yield" , "prod", "adopt_area", "pre_adopt_prod",  "post_adopt_yield", "post_adopt_prod", "pre_adopt_yield", "nonadopt_area",
                 "nonadopt_yield" , "nonadopt_prod"  ) := NULL]
dt <- unique(dt)
fillLimits <- c(round(min(dt$value, na.rm = TRUE)), ceiling(max(dt$value, na.rm = TRUE)))
cat("fillLimits: ", fillLimits)
paletteType <- "Greys"
myPalette <- colorRampPalette(brewer.pal(9, paletteType)) # 9 is max for the Greys palleteType
palette <- myPalette(4)
facetColName <- "IRRF"
numLimits <- 4
breakValues <- generateBreakValues(fillLimits = fillLimits, numLimits = numLimits, decimals = 1)
legendText <- "Yields (mt/ha)"
setnames(dt, old = "region_code.IMPACT159", new = "id")
dt <- dt[value %in% "NaN", value := NA]

g <- facetMaps(mapFile = fpusMap_SSA, DTfacetMap = dt, legendText, fillLimits, palette, facetColName, breakValues, displayOrder)
print(g)

# do by fpus

dt <- copy(dt.complete)
dt[, value := yield]
dt[, region := FPU]
fillLimits <- c(round(min(dt$value, na.rm = TRUE)), ceiling(max(dt$value, na.rm = TRUE)))
cat("fillLimits: ", fillLimits)
# paletteType <- "Greys"
# myPalette <- colorRampPalette(brewer.pal(9, paletteType)) # 9 is max for the Greys palleteType
paletteType <- "Spectral"
myPalette <- colorRampPalette(brewer.pal(11, paletteType)) 
palette <- myPalette(4)
facetColName <- "IRRF"
numLimits <- 4
breakValues <- generateBreakValues(fillLimits = fillLimits, numLimits = numLimits, decimals = 1)
legendText <- "Yields (mt/ha)"
displayOrder <- sort(unique(dt[,get(facetColName)]))

g <- facetMaps(mapFile = fpusMap_SSA, DTfacetMap = dt, legendText, fillLimits, palette, facetColName, breakValues, displayOrder)
print(g)

gg <- ggplot(fpusMap, aes(map_id = od))
gg <- gg + geom_map(aes(fill = temp.sp$value), map = worldMap, color = "white")
gg <- gg + expand_limits(x = worldMap$long, y = worldMap$lat)
gg <- gg + labs(title =  titletext, hjust = 0.5, x = NULL, y = NULL) +
  theme(plot.title = element_text(size = 10, hjust = 0.5)) +
  scale_fill_gradient(low = lowColor, high = highColor, guide = "legend", name = legendText, limits = fillLimits) +
  labs(lText = legendText) +
  #  theme(legend.position = "bottom") +
  theme(legend.justification = c(0,0), legend.position = c(0,0)) +
  # guides(lText = guide_legend(title.position="top", title.hjust = 0.5))  +
  theme(axis.ticks = element_blank(),axis.title = element_blank(), axis.text.x = element_blank(),axis.text.y = element_blank())

