#rename USAID scenarios
renameUSAIDscenarios <- function(DT) {
DT[scenario == "SSP2-NoCC-REF", scenario := "REF_NoCC"]
DT[scenario == "SSP2-HGEM2-REF", scenario := "REF_HGEM"]
DT[scenario == "SSP2-IPSL2-REF", scenario := "REF_IPSL"]
DT[scenario == "SSP2-HGEM-LoYld2", scenario := "MED"]
DT[scenario == "SSP2-HGEM-RegYld2", scenario := "REGION"]
DT[scenario == "SSP2-HGEM-HiYld2", scenario := "HIGH"]
DT[scenario == "SSP2-HGEM-HiNARS2", scenario := "HIGH_NARS"]
DT[scenario == "SSP2-HGEM-HiREFF2", scenario := "HIGH_RE"]
DT[scenario == "SSP2-HGEM-IRREXP2", scenario := "IX"]
DT[scenario == "SSP2-NoCC-IRREXP2", scenario := "IX_NoCC"]
DT[scenario == "SSP2-IPSL-IRREXP2", scenario := "IX_IPSL"]
DT[scenario == "SSP2-HGEM-IRREXP-WUE2", scenario := "IX_WUE"]
DT[scenario == "SSP2-NoCC-IRREXP-WUE2", scenario := "IX_WUE_NoCC"]
DT[scenario == "SSP2-IPSL-IRREXP-WUE2", scenario := "IX_WUE_IPSL"]
DT[scenario == "SSP2-HGEM-SWHC2", scenario := "ISW"]
DT[scenario == "SSP2-NoCC-SWHC2", scenario := "ISW_NoCC"]
DT[scenario == "SSP2-IPSL-SWHC2", scenario := "ISW_IPSL"]
DT[scenario == "SSP2-HGEM-PHL-DEV2", scenario := "RPHL"]
DT[scenario == "SSP2-HGEM-MMEFF2", scenario := "RMM"]
DT[scenario == "SSP2-HGEM-Pangloss2", scenario := "COMP"]
DT[scenario == "SSP2-NoCC-Pangloss2", scenario := "COMP_NoCC"]
DT[scenario == "SSP2-IPSL-Pangloss2", scenario := "COMP_IPSL"]
return(DT)
}
